language: node_js
node_js:
  - stable
git:
    submodules: false
before_install:
  - export DISPLAY=:99.0
  - Xvfb :99.0 -extension RANDR -ac -screen 0 1280x1024x16 > /dev/null &
before_script:
  - npm run compile
